# -*- coding: utf-8 -*-
"""Buisiniss_it_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kp8eQ3DRJRw70ObuVNtyP-KLxoGVfbKq
"""



import requests
import pandas as pd
from bs4 import BeautifulSoup
from datetime import datetime

url = "https://musicstation.be/collections/vinyl"
response = requests.get(url, timeout=20)

print("Status code:", response.status_code)

import requests
import pandas as pd
from bs4 import BeautifulSoup

url = "https://musicstation.be/collections/vinyl"
response = requests.get(url, timeout=20)
response.encoding = "utf-8"      # ensure € signs display correctly
soup = BeautifulSoup(response.text, "html.parser")

rows = []

# Same loop logic, just different product container
for vinyl in soup.select(".product-block__inner"):

    # Product title
    title_tag = vinyl.select_one("a.title")
    title = title_tag.get_text(" ", strip=True) if title_tag else None

    # Price
    price_tag = vinyl.select_one(".amount")
    price_text = price_tag.get_text(strip=True) if price_tag else None

    # Availability / product status
    status = []

    sold_out = vinyl.select_one(".product-label--soldout")
    pre_order = vinyl.select_one(".product-label--pre-order")

    if sold_out:
        status.append("Sold Out")

    if pre_order:
        status.append("Pre-Order")

    availability = ", ".join(status) if status else "Available"

    # Artist name (the bold text inside the title)
    artist_tag = vinyl.select_one("a.title span")
    artist = artist_tag.get_text(strip=True) if artist_tag else None

    rows.append({
        "artist": artist,
        "title": title,
        "price_text": price_text,
        "availability": availability,
    })

df = pd.DataFrame(rows)
df

import requests
import pandas as pd
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import time

start_url = "https://musicstation.be/collections/vinyl"
timeout = 20
headers = {
    "User-Agent": "Mozilla/5.0 (Workshop script builder)"
}
rows = []

scrape_time = datetime.now().isoformat()
next_url = start_url
page_number = 0

while next_url:
    page_number += 1
    if page_number > 50:
        break

    response = requests.get(next_url, headers=headers, timeout=timeout)
    response.raise_for_status()
    response.encoding = "utf-8"   # fixes € symbol
    soup = BeautifulSoup(response.text, "html.parser")
    items = soup.select(".product-block")

    for item in items:
        # artist
        artist_node = item.select_one("a.title span")
        artist = artist_node.get_text(" ", strip=True) if artist_node else None

        # title
        title_node = item.select_one("a.title")
        title = title_node.get_text(" ", strip=True) if title_node else None

        # price
        price_text_node = item.select_one(".amount")
        price_text = price_text_node.get_text(" ", strip=True) if price_text_node else None

        # availability
        availability_node = item.select_one(".product-label")
        availability = availability_node.get_text(" ", strip=True) if availability_node else "Available"

        rows.append({
            "artist": artist,
            "title": title,
            "price_text": price_text,
            "availability": availability,
            "scraped_at": scrape_time,
        })

    # Shopify pagination
    next_node = soup.select_one('link[rel="next"]')
    next_href = next_node.get("href") if next_node else None
    next_url = urljoin(response.url, next_href) if next_href else None

    time.sleep(1)

df = pd.DataFrame(rows)
print(f"Collected {len(df)} rows")
df.to_csv("scraped_dataset.csv", index=False)
print("Saved scraped_dataset.csv")

# Check what your DataFrame looks like right now
print(f"Columns: {list(df.columns)}")
print(f"Data types:\n{df.dtypes}")
print(f"\nFirst 3 rows:")

df["price"] = (
    df["price_text"]
      .str.replace("€", "", regex=False)      # remove euro sign
      .str.strip()                             # remove extra spaces
      .str.replace(r"\s+", ".", regex=True)    # "39 99" -> "39.99"
      .astype(float)
)

df

# See how many missing values exist per column


# Fill missing availability values with "Available"
df["availability"] = df["availability"].fillna("Available")

df

df = df.rename(columns={
    "price_text": "price_raw",     # original scraped string
    "price": "price_eur"          # cleaned numeric price
})

  # verify the renamed columns
df

# Final check
print(f"Rows: {len(df)}")
print(f"Columns: {list(df.columns)}")
print(f"Data types:\n{df.dtypes}")
print(f"\nSample:")


import os

filename = "my_dataset.csv"

if os.path.exists(filename):
    # File already exists → append without writing headers again
    df.to_csv(filename, mode="a", header=False, index=False)
else:
    # First run → create file with headers
    df.to_csv(filename, index=False)

print(f"Appended {len(df)} rows — total file now has historical data")

#from google.colab import drive
#drive.mount('/content/drive')

# How many rows and columns?


# Are there missing values?


# Does the data look right?
  # numeric summary
     # first few rows


from supabase import create_client
from datetime import datetime
import math

import os

SUPABASE_URL = os.environ["SUPABASE_URL"]
SUPABASE_KEY = os.environ["SUPABASE_KEY"]

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

scrape_time = datetime.now().isoformat()

# make sure NaNs are cleaned BEFORE upload (extra safety)
df["price_eur"] = df["price_eur"].fillna(0)

rows = []
for _, row in df.iterrows():

    price = row.get("price_eur", 0)

    # extra safety in case any NaN still slips through
    if price is None or (isinstance(price, float) and math.isnan(price)):
        price = 0

    rows.append({
        "artist":       str(row.get("artist", "")),
        "title":        str(row.get("title", "")),
        "price_eur":    float(price),
        "availability": str(row.get("availability", "")),
        "availability_numeric": int(row.get("availability_numeric", 0)),
        "scraped_at":   scrape_time,
    })

result = supabase.table("vinyls").insert(rows).execute()

print(f"✅ Inserted {len(rows)} rows into Supabase")

# Add a price tier for dashboard grouping
# .apply() runs a function on every value in the column
# The lambda checks: is the price below 20? → "Budget"
#                     below 40? → "Mid-range"
#                     otherwise → "Premium"
df["price_tier"] = df["price_eur"].apply(
    lambda p: "Budget" if p < 20
    else ("Mid-range" if p < 40 else "Premium")
)

df[["title", "price_eur", "price_tier"]]

# Clean + normalize text first
df["availability_clean"] = (
    df["availability"]
      .astype(str)
      .str.strip()
      .str.replace(r"\s+", " ", regex=True)
      .str.title()
)

# Mapping dictionary (must match cleaned format)
availability_map = {
    "Available": 3,
    "Pre-Order": 2,
    "Sold Out": 1
}

# Apply mapping safely
df["availability_numeric"] = df["availability_clean"].map(availability_map)

df[["title", "availability_clean", "availability_numeric"]]

# .str.contains() checks if the text includes "Available"
# Returns True or False for each row
# na=False means: if the value is missing, return False instead of NaN
df["in_stock"] = df["availability"].str.contains("Available", na=False)

df["in_stock"].value_counts()

# Example: drop the raw price string (you already have price_eur)
# errors="ignore" means: if the column does not exist, do nothing
df = df.drop(columns=["price_raw"], errors="ignore")
 # verify which columns remain

import math

# -------------------------
# 1. Clean availability
# -------------------------
df["availability_clean"] = (
    df["availability"]
      .astype(str)
      .str.strip()
      .str.replace(r"\s+", " ", regex=True)
      .str.title()
)

availability_map = {
    "Available": 3,
    "Pre-Order": 2,
    "Sold Out": 1
}

df["availability_numeric"] = df["availability_clean"].map(availability_map).fillna(0).astype(int)

df["in_stock"] = df["availability_clean"].str.contains("Available", na=False)

# -------------------------
# 2. Clean price safely
# -------------------------
df["price_eur"] = df["price_eur"].fillna(0)

df["price_eur"] = df["price_eur"].apply(
    lambda x: 0 if (x is None or (isinstance(x, float) and math.isnan(x))) else float(x)
)

# -------------------------
# 3. Price tier (SAFE ORDER FIX)
# -------------------------
df["price_tier"] = df["price_eur"].apply(
    lambda p: "Budget" if p < 20 else ("Mid-range" if p < 40 else "Premium")
)

rows = []

for _, row in df.iterrows():

    rows.append({
        "artist": str(row.get("artist", "")),
        "title": str(row.get("title", "")),
        "price_eur": float(row.get("price_eur", 0)),
        "price_tier": str(row.get("price_tier", "")),
        "availability": str(row.get("availability", "")),
        "availability_numeric": int(row.get("availability_numeric", 0)),
        "in_stock": bool(row.get("in_stock", False)),
        "scraped_at": scrape_time,
    })

result = supabase.table("vinyls").insert(rows).execute()

print(f"✅ Inserted {len(rows)} rows into Supabase")

